server:
  port: 8080

spring:
  application:
    name: sporty-bet-settlement
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

kafka:
  topic:
    event-outcome: event-outcome

logging:
  level:
    com.sportybet.settlement: INFO
    org.springframework.kafka: INFO
