server:
  port: 8081

spring:
  application:
    name: sporty-bet-settlement-consumer
  datasource:
    url: jdbc:h2:mem:betsdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: sport-event-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

kafka:
  topic:
    event-outcome: event-outcome

rocketmq:
  name-server: ${ROCKETMQ_NAME_SERVER:localhost:9876}
  producer:
    group: bet-settlement-producer-group
  topic:
    bet-settlements: bet-settlements

logging:
  level:
    com.sportybet.settlement.consumer: INFO
    org.springframework.kafka: INFO
    org.apache.rocketmq: INFO
